In [6]:
import pandas as pd
import numpy as np

In [7]:
data = pd.read_csv("./data/Womens Clothing E-Commerce Reviews.csv")
data.head()

Unnamed: 0  Clothing ID  Age                    Title  \
0           0          767   33                      NaN   
1           1         1080   34                      NaN   
2           2         1077   60  Some major design flaws   
3           3         1049   50         My favorite buy!   
4           4          847   47         Flattering shirt   

                                         Review Text  Rating  Recommended IND  \
0  Absolutely wonderful - silky and sexy and comf...       4                1   
1  Love this dress!  it's sooo pretty.  i happene...       5                1   
2  I had such high hopes for this dress and reall...       3                0   
3  I love, love, love this jumpsuit. it's fun, fl...       5                1   
4  This shirt is very flattering to all due to th...       5                1   

   Positive Feedback Count   Division Name Department Name Class Name  
0                        0       Initmates        Intimate  Intimates  
1                        4         General         Dresses    Dresses  
2                        0         General         Dresses    Dresses  
3                        0  General Petite         Bottoms      Pants  
4                        6         General            Tops    Blouses

In [9]:
# model LSTM deep lerning yang akan di gunakan pada pembelajran kali ini (colah LSTM)
# yang diambil datya nya di reviw text dan class name saja

# lakukan prepprosesing data yang mana data kosong dihapus
data.dropna(axis=0, subset=['Review Text','Class Name'], inplace=True)
data.head()

Unnamed: 0  Clothing ID  Age                    Title  \
0           0          767   33                      NaN   
1           1         1080   34                      NaN   
2           2         1077   60  Some major design flaws   
3           3         1049   50         My favorite buy!   
4           4          847   47         Flattering shirt   

                                         Review Text  Rating  Recommended IND  \
0  Absolutely wonderful - silky and sexy and comf...       4                1   
1  Love this dress!  it's sooo pretty.  i happene...       5                1   
2  I had such high hopes for this dress and reall...       3                0   
3  I love, love, love this jumpsuit. it's fun, fl...       5                1   
4  This shirt is very flattering to all due to th...       5                1   

   Positive Feedback Count   Division Name Department Name Class Name  
0                        0       Initmates        Intimate  Intimates  
1                        4         General         Dresses    Dresses  
2                        0         General         Dresses    Dresses  
3                        0  General Petite         Bottoms      Pants  
4                        6         General            Tops    Blouses

In [10]:
data[130:140]

Unnamed: 0  Clothing ID  Age  \
133         133          966   36   
134         134          845   65   
136         136          966   31   
137         137          836   52   
138         138          126   34   
139         139         1008   31   
140         140          829   36   
141         141          828   39   
143         143         1008   51   
144         144          829   39   

                                             Title  \
133                         Stylish and versatile!   
134           You'll smile on a humid summer's day   
136                   A new staple for my wardrobe   
137                                     Runs short   
138  Feminine alternative to your shapeless puffer   
139                  Love. love. love this skirt!!   
140                                     Pretry top   
141                                            NaN   
143                                  Great classic   
144                        Beautiful, but scratchy   

                                           Review Text  Rating  \
133  I love this vest! there are so many ways to st...       5   
134  This blouse is a perfect creation: perfect-wei...       5   
136  Love this vest! the color looks a little more ...       4   
137  I received the sky color in m online.  am defi...       4   
138  I am obsessed with peplum down coats because t...       4   
139  The silhouette and length of this skirt and le...       5   
140  Perfect for work or going out. i layered this ...       5   
141  It's a pretty top, but it runs very short. the...       4   
143  Ii'm not usually big on lace but this is so un...       5   
144  My firned tried this on and her first comment ...       3   

     Recommended IND  Positive Feedback Count   Division Name Department Name  \
133                1                        0         General         Jackets   
134                1                       12  General Petite            Tops   
136                1                        0         General         Jackets   
137                1                        0         General            Tops   
138                1                        1       Initmates        Intimate   
139                1                        1         General         Bottoms   
140                1                        0         General            Tops   
141                1                        2         General            Tops   
143                1                        0         General         Bottoms   
144                0                        9         General            Tops   

    Class Name  
133    Jackets  
134    Blouses  
136    Jackets  
137    Blouses  
138     Lounge  
139     Skirts  
140    Blouses  
141    Blouses  
143     Skirts  
144    Blouses

In [15]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer

vectoriZe = CountVectorizer()
X_train, X_test,y_train, y_test = train_test_split(
    data["Review Text"],
    data['Class Name'],
    train_size= 0.8, # sebesar 80%
    random_state= 42
)
X_train = vectoriZe.fit_transform(X_train) # ubah ke vitur transform
X_test = vectoriZe.transform(X_test) # ubah kevitur transform

In [19]:
X_train

<18102x12874 sparse matrix of type '<class 'numpy.int64'>'
	with 774531 stored elements in Compressed Sparse Row format>

In [20]:
X_test

<4526x12874 sparse matrix of type '<class 'numpy.int64'>'
	with 190268 stored elements in Compressed Sparse Row format>

In [21]:
# model neural network yang digunakan naive bayes
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB() # panggil model
# superfise lerning
nb.fit(X_train,y_train) # Trainin data
y_predik = nb.predict(X_test)# prediksi data X_test

In [22]:
from sklearn.metrics import confusion_matrix, classification_report
# mengukur performa 
confusion_matrix(y_predik,y_test)

array([[ 244,    0,   11,   15,    4,    8,    2,  102,    1,    0,    6,
           4,    0,    1,    7,    0,    3,    7,    2],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0],
       [  59,    0, 1202,   33,   12,   56,    2,   85,    2,    2,   28,
          23,   60,   16,  105,    9,   47,   30,   17],
       [   0,    0,    0,    7,    0,    1,    0,    1,    0,    0,    0,
           0,    1,    0,    1,    0,    7,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,   10,    0,    1,    0,    0,    0,
           2,    0,    0,    0,    0,    1,    0,    0],
       [   1,    0,    0,    0,    0,    1,  175,    2,    0,    7,    5,
           0,   25,    5,    0,    1,    0,    0,    1],
       [ 281,    0,   44,  126,   12,   60,   13,  723,   23,    4,   50,
         

In [23]:
print(classification_report(y_predik, y_test))

                precision    recall  f1-score   support

       Blouses       0.42      0.59      0.49       417
Casual bottoms       0.00      0.00      0.00         0
       Dresses       0.95      0.67      0.79      1788
    Fine gauge       0.03      0.39      0.06        18
     Intimates       0.00      0.00      0.00         0
       Jackets       0.07      0.71      0.12        14
         Jeans       0.75      0.78      0.77       223
         Knits       0.78      0.47      0.59      1533
      Layering       0.00      0.00      0.00         0
       Legwear       0.03      1.00      0.06         1
        Lounge       0.00      0.00      0.00         2
     Outerwear       0.00      0.00      0.00         1
         Pants       0.60      0.55      0.57       293
        Shorts       0.00      0.00      0.00         0
        Skirts       0.17      0.90      0.29        30
         Sleep       0.03      1.00      0.05         1
      Sweaters       0.39      0.54      0.45  

d:\laragonApp\laragon\bin\python\python-3.10\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
d:\laragonApp\laragon\bin\python\python-3.10\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
d:\laragonApp\laragon\bin\python\python-3.10\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [25]:
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
MAX_NB_WORDS = 50000
MAX_SEQUENCE_LENGTH = 250
EMBEDDING_DIM = 100
tokenizer = Tokenizer(num_words=MAX_NB_WORDS, filters='!"#$%&()*+,-./:;<=>?@[\]^_`{|}~', lower=True)
tokenizer.fit_on_texts(data["Review Text"].values)
word_index = tokenizer.word_index
print('Found %s unique tokens.' % len(word_index))
X = tokenizer.texts_to_sequences(data["Review Text"].values)
X = pad_sequences(X, maxlen=MAX_SEQUENCE_LENGTH)
print("shape of data tensor:", X.shape)

Found 15581 unique tokens.
shape of data tensor: (22628, 250)


In [29]:
Y = pd.get_dummies(data['Class Name']).values
print("shape of label tensor: ", Y.shape)
Y

shape of label tensor:  (22628, 20)


array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [27]:
X_train,X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.10, random_state=42)
print(X_train.shape, Y_train.shape)
print(X_test.shape, Y_test.shape)

(20365, 250) (20365, 20)
(2263, 250) (2263, 20)


In [31]:
# model lstm
from keras.models import Sequential
from keras.layers import Embedding,SpatialDropout1D,LSTM,Dense
model = Sequential()
model.add(Embedding(MAX_NB_WORDS,EMBEDDING_DIM,input_length=X.shape[1]))
model.add(SpatialDropout1D(0.2))
model.add(LSTM(100,dropout=0.2,recurrent_dropout=0.2))
model.add(Dense(20,activation='softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

epochs = 5
batch_size = 64
model.fit(X_train,Y_train,epochs=epochs,batch_size=batch_size,validation_split=0.1)

Epoch 1/5
287/287 [==============================] - 382s 1s/step - loss: 2.2097 - accuracy: 0.3056 - val_loss: 2.1068 - val_accuracy: 0.3378
Epoch 2/5
287/287 [==============================] - 414s 1s/step - loss: 1.7884 - accuracy: 0.4350 - val_loss: 1.6377 - val_accuracy: 0.4821
Epoch 3/5
287/287 [==============================] - 391s 1s/step - loss: 1.5913 - accuracy: 0.4810 - val_loss: 1.4771 - val_accuracy: 0.5101
Epoch 4/5
287/287 [==============================] - 451s 2s/step - loss: 1.5728 - accuracy: 0.4849 - val_loss: 1.5337 - val_accuracy: 0.4983
Epoch 5/5
287/287 [==============================] - 420s 1s/step - loss: 1.3629 - accuracy: 0.5503 - val_loss: 1.3609 - val_accuracy: 0.5547


In [32]:
y_predik = model.predict(X_test)
y_predik.shape

71/71 [==============================] - 3s 38ms/step


(2263, 20)

In [35]:
from mlxtend.preprocessing import one_hot
import numpy as np
resuld = np.where(y_predik[0] == np.amax(y_predik[0]))
one_hot(resuld[0])

array([[0., 0., 0., 1.]])

In [33]:
model.save('./data/model.h5')
print("Saved model to disk")

Saved model to disk


d:\laragonApp\laragon\bin\python\python-3.10\lib\site-packages\keras\src\engine\training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(
